### ISSUE TITLE
Resolution skewed, it seems like problems in the definition aspect ratio

### ISSUE THREAD

**Issue by PanCrucian** [ant-media/LiveVideoBroadcaster#16]
```
10-27 15:07:37.398 29575-29636/io.antmedia.android.livevideopublisher I/System.out: --- camera opened --- 
10-27 15:07:37.398 29575-29636/io.antmedia.android.livevideopublisher E/Camera: getSupportedPreviewSizes str:2560x1440,1920x1080,1440x1080,1280x960,1280x720,1080x1080,960x720,720x720,720x480,640x480,352x288,320x240,176x144
10-27 15:07:37.398 29575-29636/io.antmedia.android.livevideopublisher E/suojp: getSupportedPreviewSizes th:java.lang.Throwable
                                                                                   at android.hardware.Camera$Parameters.getSupportedPreviewSizes(Camera.java:3194)
                                                                                   at io.antmedia.android.broadcaster.LiveVideoBroadcaster.setCameraParameters(LiveVideoBroadcaster.java:531)
                                                                                   at io.antmedia.android.broadcaster.LiveVideoBroadcaster.access$800(LiveVideoBroadcaster.java:53)
                                                                                   at io.antmedia.android.broadcaster.LiveVideoBroadcaster$7.doInBackground(LiveVideoBroadcaster.java:463)
                                                                                   at io.antmedia.android.broadcaster.LiveVideoBroadcaster$7.doInBackground(LiveVideoBroadcaster.java:436)
                                                                                   at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                                   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                   at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                   at java.lang.Thread.run(Thread.java:818)
10-27 15:07:37.398 29575-29636/io.antmedia.android.livevideopublisher E/Camera: getSupportedPreviewSizes new str:1920x1080,1440x1080,1280x960,1280x720,1080x1080,960x720,720x720,720x480,640x480,352x288,320x240,176x144
10-27 15:07:37.399 29575-29636/io.antmedia.android.livevideopublisher E/DKdebugMsg: setPreviewSize########################## 1 ############,  width = 720, height = 720
10-27 15:07:37.399 29575-29636/io.antmedia.android.livevideopublisher E/Camera: setPreviewSize:io.antmedia.android.livevideopublisher:720x720
10-27 15:07:37.399 29575-29636/io.antmedia.android.livevideopublisher E/DKdebugMsg: setPreviewSize########################## 2 ############
10-27 15:07:37.402 29575-30028/io.antmedia.android.livevideopublisher I/DKdebugMsg: ---setParameters---PackageName = io.antmedia.android.livevideopublisher
10-27 15:07:37.402 29575-30028/io.antmedia.android.livevideopublisher I/DKdebugMsg: ---setParameters---ActivityName = io.antmedia.android.liveVideoBroadcaster.LiveVideoBroadcasterActivity
10-27 15:07:37.402 29575-30028/io.antmedia.android.livevideopublisher I/DKdebugMsg: ---setParameters---mLetvTrace = io.antmedia.android.livevideopublisher.LETV.io.antmedia.android.liveVideoBroadcaster.LiveVideoBroadcasterActivity
10-27 15:07:37.433 29575-30016/io.antmedia.android.livevideopublisher I/System.out: //Tell the UI thread to enable the camera preview.
```
Device LeEco le 2, 1920x1080, API 23, Bug sample: https://goo.gl/FdWPpU and https://goo.gl/bR5LMh

**Comment by PanCrucian** [comment]
@mekya check it pleaase

**Comment by PanCrucian** [comment]
I found where bug is https://goo.gl/ganx7o It is necessary to collect resolutions not by "mod", by aspect of the ratio

**Comment by mekya** [comment]
Yeah you are right. Is it possible to make a pull request for this issue?

**Comment by PanCrucian** [comment]
Ok i make it

**Comment by mekya** [comment]
Closing this issue. Thank you
