### ISSUE TITLE
Crash in playing rtmp link of antmedia

### ISSUE THREAD

**Issue by nagendraK6** [ant-media/LiveVideoBroadcaster#21]
Created an ant media server RTMP.
I can play in ffplay and vlc player with the link format rtmp://<server_ip>/LiveApp/<some_unique_id_from_antmedia>

I am trying to run this link in LiveVideoBroadcaster and getting exception

-08 20:33:27.515 7557-7557/io.antmedia.android.livevideopublisher E/EventLogger: internalError [2.71, loadError]
                                                                                   java.io.IOException: Connection to server is lost
                                                                                       at net.butterflytv.rtmp_client.RtmpClient.nativeRead(Native Method)
                                                                                       at net.butterflytv.rtmp_client.RtmpClient.read(RtmpClient.java:96)
                                                                                       at io.antmedia.android.liveVideoPlayer.RtmpDataSource.read(RtmpDataSource.java:62)
                                                                                       at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:257)
                                                                                       at com.google.android.exoplayer2.extractor.DefaultExtractorInput.advancePeekPosition(DefaultExtractorInput.java:132)
                                                                                       at com.google.android.exoplayer2.extractor.DefaultExtractorInput.peekFully(DefaultExtractorInput.java:113)
                                                                                       at com.google.android.exoplayer2.extractor.DefaultExtractorInput.peekFully(DefaultExtractorInput.java:123)
                                                                                       at com.google.android.exoplayer2.extractor.mkv.Sniffer.sniff(Sniffer.java:50)
                                                                                       at com.google.android.exoplayer2.extractor.mkv.MatroskaExtractor.sniff(MatroskaExtractor.java:312)
                                                                                       at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:701)
                                                                                       at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:636)
                                                                                       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                       at java.lang.Thread.run(Thread.java:818)

**Comment by nagendraK6** [comment]
Resolved it by adding live=1 at the end of url
