### ISSUE TITLE
Error while trying to stream rtmp url

### ISSUE THREAD

**Issue by maximus9600** [ant-media/LiveVideoBroadcaster#24]
I have my own  RTMP streaming url  setup using nginx. i am trying to use on the live video player. 

I am getting this error:
`playerFailed [10.22]
                                                                                   com.google.android.exoplayer2.ExoPlaybackException
                                                                                       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:345)
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                       at android.os.Looper.loop(Looper.java:154)
                                                                                       at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                       at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                                    Caused by: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor) could read the stream.`

I tried playing it on VLC and it works. The codec of the video is H264-MPEG4 AVC. Could this be the reason?

**Comment by pvllnspk** [comment]
@maximus9600 Any news?

**Comment by mekya** [comment]
closing this issue for the inactivity. Please reopen it if are still having this problem.
