### ISSUE TITLE
IllegalStateException at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)

### ISSUE THREAD

**Issue by anujyadav2705** [ant-media/LiveVideoBroadcaster#47]
**Crush in Samsung devices.**

USER_COMMENT=null
ANDROID_VERSION=7.0
APP_VERSION_NAME=3.1.61.staging
BRAND=samsung
PHONE_MODEL=SM-G925I
CUSTOM_DATA=
STACK_TRACE=java.lang.IllegalStateException
at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:2505)
at io.antmedia.android.broadcaster.encoder.AudioEncoder.encodeAudio(AudioEncoder.java:78)
at io.antmedia.android.broadcaster.encoder.AudioHandler.handleMessage(AudioHandler.java:64)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by SelimEmre** [comment]
Hi @anujyadav2705,
Thank you for your interest. Please give more detail for your crush. Which Ant Media Server version you used ? Which Ant Media Server Application (LiveApp or WebRTCApp) do you use? Did you watch our [YouTube ](https://www.youtube.com/watch?v=-azHuHdqBbE) video ? 

Best Regards,
Selim

**Comment by anujyadav2705** [comment]
Hello @SelimEmre 

i am facing crash on Samsung device while start LIve Stream
i am using 
https://github.com/ant-media/LiveVideoBroadcaster  sample for LiveApp..
 i am using Youtube RTMP url..

here is my crash report..

USER_COMMENT=null
ANDROID_VERSION=7.0
APP_VERSION_NAME=3.1.61.staging
BRAND=samsung
PHONE_MODEL=SM-G925I
CUSTOM_DATA=
STACK_TRACE=java.lang.IllegalStateException
at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:2505)
at io.antmedia.android.broadcaster.encoder.AudioEncoder.encodeAudio(AudioEncoder.java:78)
at io.antmedia.android.broadcaster.encoder.AudioHandler.handleMessage(AudioHandler.java:64)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.os.HandlerThread.run(HandlerThread.java:61)

Thanks & Regards

**Comment by SelimEmre** [comment]
Hi @anujyadav2705,
Thank your for your interest. Firstly, please use Ant Media Server Latest Version. Please check sections in below:
1- Android Studio MainActivity.java should like image.
![android studio 1](https://user-images.githubusercontent.com/9084130/52482583-b57c9000-2bc2-11e9-8dc3-147873a9aeb1.JPG)
2-Please Be sure to send it to StreamId in LiveApp.
![streamid2](https://user-images.githubusercontent.com/9084130/52483020-dee9eb80-2bc3-11e9-9fdb-abf7e3e4bb9d.png)
![livebroadcastapp](https://user-images.githubusercontent.com/9084130/52482785-3a67a980-2bc3-11e9-8e3e-0300c16d94af.jpg)

I hope i could help you. Please inform us if you have any problem. Good Luck!

Best Regards,
Selim

**Comment by anujyadav2705** [comment]
@SelimEmre i not using Ant media server for liveStreaming.... i am use Youtube RTMP url for livestreaming..

**Comment by SelimEmre** [comment]
Hi @anujyadav2705,
Sorry for the delay.  Nowadays, we're dealing with the new version. You should edit RTMP_BASE_URL in below. You probably didn't add / end the url. Due to RTMP Url, you had experienced problems.
`public static final String RTMP_BASE_URL = "rtmp://a.rtmp.youtube.com/live2/";`

Thanks,
Selim

**Comment by mekya** [comment]
Issues tab will be closed for this project. Please submit your issues on https://github.com/ant-media/Ant-Media-Server
