### ISSUE TITLE
Screen crash on view onStop

### ISSUE THREAD

**Issue by clamorious** [ant-media/LiveVideoBroadcaster#7]
When minimize the app on broadcast view and back , the screen crashes, a loop starts on Android Monitor and screen blackout, the log is:
`
io.antmedia.android.livevideopublisher I/CameraSurfaceRenderer: Drawing before incoming texture size set; skipping`

I'll try fix by myself if someone know some way to fix this, please, answer this issue.

Thank you.

**Comment by mekya** [comment]
Is this the only log that you can get from logcat? If not, is it possible to send more log about this issue. 

Regards,

**Comment by clamorious** [comment]
Hello mekya,

Thanks for answer, here is more logs as you requested:

```
java.lang.IllegalStateException: setRenderer has already been called for this instance.
    at android.opengl.GLSurfaceView.checkRenderThreadState(GLSurfaceView.java:1821)
    at android.opengl.GLSurfaceView.setRenderer(GLSurfaceView.java:348)
    at io.antmedia.android.broadcaster.LiveVideoBroadcaster.init(LiveVideoBroadcaster.java:173)
    at com.eventials.eventialsbroadcaster.LiveVideoBroadcasterActivity$1.onServiceConnected(LiveVideoBroadcasterActivity.java:98)
    at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1223)
    at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1240)
    at android.os.Handler.handleCallback(Handler.java:746)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5459)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
I/System.out: --- releaseCamera call in doInBackground --- 
I/System.out: --- camera opened ---
 ```

Regards.

**Comment by mekya** [comment]
I see, I guess the problem. 

Is it possible to let me know the exact scenario?

You start broadcasting. 
While you broadcasting you press the home or back button?
When you return back the app, it throws this exception right?

Regards,

**Comment by clamorious** [comment]
When I am at broadcasting view, not broadcasting (but when broadcasting happen the same thing)
), just the view open, I press the home button or the button to switch to other app, I back to the app and it throws this exception.

Regards.

**Comment by mekya** [comment]
Hi @clamorious 

Please apply the below patch and let me know if it works or any other troubles.

```
diff --git a/app/src/main/java/io/antmedia/android/liveVideoBroadcaster/LiveVideoBroadcasterActivity.java b/app/src/main/java/io/antmedia/android/liveVideoBroadcaster/LiveVideoBroadcasterActivity.java
index 076bfde..a0b231c 100644
--- a/app/src/main/java/io/antmedia/android/liveVideoBroadcaster/LiveVideoBroadcasterActivity.java
+++ b/app/src/main/java/io/antmedia/android/liveVideoBroadcaster/LiveVideoBroadcasterActivity.java
@@ -65,9 +65,11 @@ public class LiveVideoBroadcasterActivity extends AppCompatActivity {
                                        IBinder service) {
             // We've bound to LocalService, cast the IBinder and get LocalService instance
             LiveVideoBroadcaster.LocalBinder binder = (LiveVideoBroadcaster.LocalBinder) service;
-            mLiveVideoBroadcaster = binder.getService();
-            mLiveVideoBroadcaster.init(LiveVideoBroadcasterActivity.this, mGLView);
-            mLiveVideoBroadcaster.setAdaptiveStreaming(true);
+            if (mLiveVideoBroadcaster == null) {
+                mLiveVideoBroadcaster = binder.getService();
+                mLiveVideoBroadcaster.init(LiveVideoBroadcasterActivity.this, mGLView);
+                mLiveVideoBroadcaster.setAdaptiveStreaming(true);
+            }
             mLiveVideoBroadcaster.openCamera(Camera.CameraInfo.CAMERA_FACING_FRONT);
         }
         @Override
```

**Comment by clamorious** [comment]
Hi @mekya 
The problem was solved with this change.
Thank you so much!
